# Generated by Django 5.2.3 on 2025-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sell',
            new_name='SoldData',
        ),
    ]
