# Generated by Django 5.2.3 on 2025-07-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_alter_order_status_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldData',
        ),
    ]
