# Generated by Django 5.2.3 on 2025-07-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_delete_solddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(default='Kathmandu'),
        ),
    ]
